config/routes.rb
FarmlyWed::Application.routes.draw do
  devise_for :users
  devise_for :admins

  # Admin
  namespace :admin do
    root to: 'contacts#index'
    resources :contacts, only: [:index,:show]
    resources :weddings, only: :index
    resources :users, only: :index
  end

  resources :weddings
  resource :payments

  # Invitations
  get 'invitations/stats' => 'invitations#stats', as: :invitations_stats
  post 'invitations/cities' => 'invitations#cities'
  post 'addresses/lookup' => 'addresses#lookup'
  post 'invitations/search' => 'searches#create', as: :search

  resources :invitations do
    member do
      post :add_guest
    end
  end

  # Public pages
  resources :contacts, only: [:create]
  get 'contact', to: 'contacts#new', as: :contact

  root to: 'pages#index'

  # Nothing below this route
  get ':page' => 'pages#show', as: :page
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :wedding
  has_many :guests
  belongs_to :group

  validates :zip_code, format: {with: /\d{5}(-\d{4})?/, allow_blank: true, message: I18n.translate('validations.invitations.zip_code')}

  scope :missing_address, -> { where "street = '' OR city = ''" }
  scope :three_or_more_kids, -> { where "kids >= 3" }
  scope :brides_family, -> { joins(:group).where(['groups.name = ?', 'Bride']) }
  scope :grooms_family, -> { joins(:group).where(['groups.name = ?', 'Groom']) }
  scope :friends, -> { joins(:group).where(['groups.name = ?', 'Friends']) }
  scope :no_label, -> { where outer_label: nil }
  scope :not_sent, -> { where sent_at: nil }
  scope :sent, -> { where ['sent_at IS NOT NULL OR sent_at != ?', ""] }
  scope :search, lambda {|query|
    joins(:guests).where('guests.name LIKE :query OR invitations.outer_label LIKE :query', query: "%#{query}%")
  }
  scope :rsvp_yes, -> { where ['rsvp_response = ?', true] }
  scope :rsvp_no, -> { where ['rsvp_response = ?', false] }
  scope :rsvp_none, -> { where 'rsvp_response IS NULL' }

  accepts_nested_attributes_for :guests, allow_destroy: true, reject_if: proc {|attributes| attributes[:name].blank?}

  def sent?
    sent_at.present?
  end

  def rsvp_status_bootstrap_icon_name
    case rsvp_response
    when true
      'icon-thumbs-up'
    when false
      'icon-thumbs-down'
    when nil
      'icon-question-sign'
    end
  end

  def rsvp_response= value
    case value
    when 'true'
      response = true
    when 'false'
      response = false
    when ''
      response = nil
    end
    write_attribute(:rsvp_response, response)
  end

  def address
    "#{self.street} #{self.city}, #{self.state} #{self.zip_code}"
  end

  def outer_label
    return 'No Label' if read_attribute(:outer_label).blank? || read_attribute(:outer_label).nil?
    read_attribute(:outer_label)
  end

  def sent_at
    read_attribute(:sent_at).present?
  end

  def sent_at= value
    if value == 'true'
      write_attribute(:sent_at, Time.now)
    else
      write_attribute(:sent_at, nil)
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :authenticate_user!
  prepend_before_filter :reset_filter, only: [:index]
  append_before_filter :limit_trial_invitations, only: [:new, :create]
  layout 'members'
  respond_to :html, :js

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = current_wedding.invitations.send(@filter.method)
    respond_with @invitations
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = current_wedding.invitations.find(params[:id])
    respond_with @invitation
  end

  # GET /invitations/new
  # GET /invitations/new.json
  def new
    @invitation = Invitation.new
    2.times { @invitation.guests.build }
    respond_with @invitation
  end

  # GET /invitations/1/edit
  def edit
    @invitation = current_wedding.invitations.find(params[:id])
    @invitation.guests.build
    respond_with @invitation
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = current_wedding.invitations.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to invitations_path(filter: session[:filter]), notice: "#{@invitation.outer_label} was added to the invitation list!" }
        format.json { render json: @invitation, status: :created, location: @invitation }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.json
  def update
    @invitation = current_wedding.invitations.find(params[:id])

    respond_to do |format|
      if @invitation.update_attributes(invitation_params)
        format.html { redirect_to invitations_path(filter: session[:filter]), notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation = current_wedding.invitations.find(params[:id])
    @invitation.destroy
    respond_with @invitation, location: invitations_path(filter: @filter.id)
  end

  # GET /invitations/cities/:city
  def cities
    cities = current_wedding.invitations.select('DISTINCT city').where(['city LIKE ?', "#{params[:city]}%"]).map(&:city)
    render json: cities
  end

  # GET /invitations/stats
  def stats
    missing_address_count = current_wedding.invitations.missing_address.count
    guests_rsvp_yes_count = current_wedding.guests.rsvp_yes.count
    guests_rsvp_no_count = current_wedding.guests.rsvp_no.count
    guests_rsvp_none_count = current_wedding.guests.rsvp_none.count
    invitations_count = current_wedding.invitations.count
    guest_count = current_wedding.invitations.sum(:size)
    kids_count = current_wedding.invitations.sum(:kids)

    render json: {
      missing_address: missing_address_count,
      invitations_rsvp_yes: guests_rsvp_yes_count,
      invitations_rsvp_no: guests_rsvp_no_count,
      invitations_rsvp_none: guests_rsvp_none_count,
      invitations: invitations_count,
      guests: guest_count,
      kids: kids_count
    }
  end

  def reset_filter
    if params[:filter].blank? || params[:filter] != session[:filter]
      session.delete(:filter)
    end
  end
  hide_action :reset_filter

  private

  def invitation_params
    params[:invitation].permit(:outer_label, :city, :kids, :size, :notes,
                               :state, :street, :wedding_id, :group_id,
                               :zip_code, :sent_at, :rsvp_response,
                               :guests_attributes => [:name, :invitation_id])
  end

  def limit_trial_invitations
    if current_wedding.at_max_trial_invitations?
      @at_max_trial_invitations = true
      flash[:warning] = 'You have reached the maximum invitations for a trial account. Please add a payment method to continue.'
      redirect_to invitations_path
    end
  end
end

app/views/invitations/_filters.html.haml
%ul.list-inline
  - Filter.all.each do |filter|
    - if @filter.id == filter.id
      = link_to invitations_path, class: 'remove-filter btn btn-primary' do
        \&times;
        \#{filter.name}
    - else
      %button.btn.btn-primary{type: 'button', href: invitations_path(filter: filter.id)}
        = filter.name

app/views/invitations/_form.html.haml
= form_for @invitation, :html => { remote: request.xhr?} do |f|
  .form-group
    = f.label :outer_label, '* Outer Label'
    = f.text_field :outer_label, :required => true, :class => 'form-control'
    %i.icon-question-sign.icon-large.help-tip{:title => 'The Outer Label', 'data-content' => I18n.translate('help.invitations.invitation_label')}
  = render partial: 'invitations/guest_fields', collection: @invitation.guests, as: :guest, locals: {f: f}
  .form-group
    = f.label :street
    = f.text_field :street, :class => 'form-control'
  .form-group
    = f.label :city
    = f.text_field :city, :class => 'form-control', :autocomplete => 'off'
  .form-group
    = f.label :state
    = f.select :state, US_STATES, :class => 'form-control'
  .form-group
    = f.label :zip_code
    = f.text_field :zip_code, :class => 'form-control'
    %span.help-inline 5 or 9-digit zip code
  .form-group
    = f.label :size
    = f.number_field :size, :class => 'form-control'
  .form-group
    = f.label :kids
    = f.number_field :kids, :class => 'form-control'
  .checkbox
    = f.label :sent_at_true  do
      = f.radio_button :sent_at, true
      Sent
    = f.label :sent_at_false do
      = f.radio_button :sent_at, false
      Not Sent
  .checkbox
    = f.label :rsvp_response_true do
      = f.radio_button :rsvp_response, true
      Coming
    = f.label :rsvp_response_false do
      = f.radio_button :rsvp_response, false
      Not Coming
    = f.label :rsvp_response do
      = f.radio_button :rsvp_response, ''
      No Response
  .form-group
    = link_to 'Notes', '#', :id => 'invitation_notes_toggle'
  #invitation_notes_container.form-group.hide
    = f.label :notes
    = f.text_area :notes, :class => 'form-control', :rows => 7
  .form-group
    = f.label :group_id
    = f.collection_select :group_id, Group.all, :id, :name, :include_blank => 'Choose a group', :class => 'form-control'

app/views/invitations/_form_actions.html.haml
= submit_tag 'Save', :class => 'btn btn-primary', :form => @invitation.new_record? ? 'new_invitation' : "edit_invitation_#{@invitation.id}"
= link_to t('.cancel', :default => t("helpers.links.cancel")), '#', :class => 'btn', 'data-dismiss' => 'modal'

app/views/invitations/_guest_fields.html.haml
= f.fields_for :guests, guest do |guests_fields|
  .form-group
    = guests_fields.label :name, 'Guest Name'
    = guests_fields.text_field :name, class: 'form-control'
    = link_to 'Lookup Address', '#', class: 'address_lookup'
    - if guest.persisted?
      = guests_fields.label :_destroy do
        = guests_fields.check_box :_destroy
        Delete

app/views/invitations/_invitation.html.haml
%tr{:id => "invitation_#{invitation.id}"}
  %td
    - if invitation.notes.present?
      %i.icon-question-sign.need-info{:title => 'Notes/Questions', 'data-content' => simple_format(invitation.notes)}
    = link_to invitation.outer_label, edit_invitation_path(invitation), :title => 'Edit'
  %td= truncate(invitation.address)
  %td #{invitation.size} / #{invitation.kids}
  %td= invitation.group.name if invitation.group.present?
  %td= link_to t('.destroy', :default => t("helpers.links.destroy")), invitation_path(invitation), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger', :remote => true

app/views/invitations/_legend.html.haml
%h3 Icon Legend
%ul.inline
  %li
    %span.icon.icon-envelope
    Invitation Sent
  %li
    %span.icon.icon-thumbs-up
    RSVP Attending
  %li
    %span.icon.icon-thumbs-down
    RSVP Not Attending
  %li
    %span.icon.icon-question-sign
    RSVP Unknown

app/views/invitations/create.js.erb
<% if @invitation.valid? && @invitation.persisted? -%>
  $('.modal').modal('toggle');
  $('.modal').find('.modal-header').empty();
  $('.modal').find('.modal-body').empty();
  $('table#invitation-list').append('<%= escape_javascript(render @invitation) %>');
  loadGuestStats();
<% else -%>
  $('.modal-body #error_explanation').remove();
  $('.modal-body').prepend('<%= escape_javascript(render(partial: 'shared/errors', locals: {errors: @invitation.errors})) %>');
<% end -%>

app/views/invitations/destroy.js.erb
$('tr#invitation_<%= params[:id] %>').remove();
loadGuestStats();

app/views/invitations/edit.html.haml
- model_class = Invitation
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render partial: "form"
= render partial: 'form_actions'

app/views/invitations/index.html.haml
- model_class = Invitation
= content_for :heading do
  .page-header
    %h1=t '.title', :default => model_class.model_name.human.pluralize
= content_for :filters do
  = render partial: 'filters'
%table#invitation-list.table.table-striped.table-condensed
  %thead
    %tr
      %th= model_class.human_attribute_name(:outer_label)
      %th= model_class.human_attribute_name(:address)
      %th Guests / Kids
      %th= model_class.human_attribute_name(:group)
      %th
  %tbody
    = render @invitations
= link_to new_invitation_path, :class => 'btn btn-primary' do
  %span.icon.icon-plus-sign
  New Invitation

app/views/invitations/new.html.haml
- model_class = Invitation
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"
= render :partial => "form_actions"

app/views/invitations/new.js.erb
<% if @at_max_trial_invitations == true %>
  $('.modal-header h3').html("Trial Account");
  $('.modal-body').html('<%= escape_javascript(flash[:warning]) %>');
<% else %>
  $('.modal-header h3').html("Add a invitation");
  $('.modal-body').html('<%= escape_javascript(render 'form') %>');
  $('.modal-footer').append('<%= escape_javascript(render 'form_actions') %>');
<% end %>
$('.modal').modal('toggle');

app/views/invitations/show.html.haml
- model_class = Invitation
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @invitation.first_name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @invitation.last_name
%p
  %strong= model_class.human_attribute_name(:street) + ':'
  %br
  = @invitation.street
%p
  %strong= model_class.human_attribute_name(:city) + ':'
  %br
  = @invitation.city
%p
  %strong= model_class.human_attribute_name(:state) + ':'
  %br
  = @invitation.state
%p
  %strong= model_class.human_attribute_name(:zip) + ':'
  %br
  = @invitation.zip
%p
  %strong= model_class.human_attribute_name(:additional_guests) + ':'
  %br
  = @invitation.additional_guests
%p
  %strong= model_class.human_attribute_name(:kids) + ':'
  %br
  = @invitation.kids
%p
  %strong= model_class.human_attribute_name(:group_id) + ':'
  %br
  = @invitation.group.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), invitations_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_invitation_path(@invitation), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), invitation_path(@invitation), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'