config/routes.rb
FarmlyWed::Application.routes.draw do
  devise_for :users
  devise_for :admins

  # Admin
  namespace :admin do
    root to: 'contacts#index'
    resources :contacts, only: [:index,:show]
    resources :weddings, only: :index
    resources :users, only: :index
  end

  resources :weddings
  resource :payments

  # Invitations
  get 'invitations/stats' => 'invitations#stats', as: :invitations_stats
  post 'invitations/cities' => 'invitations#cities'
  post 'addresses/lookup' => 'addresses#lookup'
  post 'invitations/search' => 'searches#create', as: :search

  resources :invitations do
    member do
      post :add_guest
    end
  end

  # Public pages
  resources :contacts, only: [:create]
  get 'contact', to: 'contacts#new', as: :contact

  root to: 'pages#index'

  # Nothing below this route
  get ':page' => 'pages#show', as: :page
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#main-navbar'}}
        %span.sr-only
          Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand.brand{:href => '/'} FarmlyWed
    #main-navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to invitations_path do
            %span.glyphicon.glyphicon-envelope
            Invitations
        %li
          = link_to new_invitation_path do
            %span.glyphicon.glyphicon-plus
            New Invitation
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to destroy_user_session_path, method: :delete do
            %span.glyphicon.glyphicon-log-out
            Sign Out

app/views/layouts/_stats.html.haml
%button.btn.btn-default{type: 'button'}
  No Address
  %span#stats-missing-address.badge
%button.btn.btn-default{type: 'button'}
  RSVP Coming
  %span#stats-rsvp-coming.badge
%button.btn.btn-default{type: 'button'}
  RSVP Not Coming
  %span#stats-rsvp-not-coming.badge
%button.btn.btn-default{type: 'button'}
  RSVP Not Received
  %span#stats-rsvp-none.badge.badge-info
%button.btn.btn-default{type: 'button'}
  Total Invitations
  %span#stats-invitations.badge.badge-info
%button.btn.btn-default{type: 'button'}
  Guests
  %span#stats-total.badge.badge-success
%button.btn.btn-default{type: 'button'}
  Kids
  %span#stats-kids.badge.badge-success

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title FarmlyWed - Admin 
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    
  %body
    .container-narrow
      .masthead
        %ul.nav.nav-pills.pull-right
          %li
            - if admin_signed_in?
              = link_to 'Sign Out', destroy_user_session_path, method: :delete
            - else
              = link_to 'Sign In', new_user_session_path
          %li
            = link_to 'Weddings', admin_weddings_path
          %li
            = link_to 'Users', admin_users_path
          %li
            = link_to 'Contacts', admin_contacts_path
        %h2.muted 
          = link_to 'FarmlyWed Admin', admin_root_path, class: 'brand'
      %hr/
      = yield
      %hr/
      .footer
        %p © FarmlyWed 2013
  = javascript_include_tag "application"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FarmlyWed - Easily Prepare and Manage Your Wedding Guest Invitation List" %></title>
    <meta name="description" content="With FarmlyWed you build a guest list for your wedding, as a member you can invite family to help you with your wedding guests invitations">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">FarmlyWed</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to 'Invitations', invitations_path %></li>
                <li><%= link_to 'New Invitation', new_invitation_path, :remote => true %></li>
              <% end %>
              <li>
              <% if user_signed_in? %>
                <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
              <% else %>
                <%= link_to 'Login', new_user_session_path %>
              <% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <%- if user_signed_in? %>
          <div class="span3">
            <ul class="unstyled">
              <li>
              <%= form_tag invitations_path, :method => :get, :id => 'filter' do %>
                <%= select_tag :filter_id, options_for_select(Filter.all.map {|filter| [filter.name, filter.id]}, :selected => @filter.id), :class => 'input-medium' %>
                <%= submit_tag 'Apply Filter' %>
              <% end %>
              </li>
              <li>
              <%= link_to 'Reset Filters', guests_path %>
              </li>
            </ul>
            <%= render :partial => 'layouts/stats' %>
          </div><!--/span-->
        <%- end %>
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
      </footer>
    </div> <!-- /container -->
    <div id="farmlywed-modal" class="modal hide fade" data-backdrop="static">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3></h3>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
      </div>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">$(document).ready(function() { loadGuestStats(); });</script>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title FarmlyWed - Easily Prepare and Manage Your Wedding Guest Invitation List
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "With FarmlyWed you build a guest list for your wedding, as a member you can invite family to help you with your wedding guests invitations", :name => "description"}/
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = stylesheet_link_tag "http://cdn-images.mailchimp.com/embedcode/slim-081711.css", media: "all"
    :css
      #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    
  %body
    .container-narrow
      .masthead
        %ul.nav.nav-pills.pull-right
          %li= link_to 'Pricing', page_path('pricing')
          %li= link_to 'About', page_path('about')
          %li= link_to 'FAQs', page_path('faqs')
          %li= link_to 'Contact', page_path('contact')
          - if user_signed_in?
            %li= link_to 'Invitations', invitations_path
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          - else
            %li
              = link_to new_user_session_path do
                %span.icon.icon-user
                Sign In
        %h2.muted 
          = link_to 'FarmlyWed', root_path, class: 'brand'
      %hr/
      = yield
      %hr/
      .footer
        %p © FarmlyWed 2013
  = javascript_include_tag "application"
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-40198134-1', 'farmlywed.com');
      ga('send', 'pageview');

app/views/layouts/members.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "FarmlyWed - Easily Prepare and Manage Your Wedding Guest Invitation List"
    %meta{:content => "With FarmlyWed you build a guest list for your wedding, as a member you can invite family to help you with your wedding guests invitations", :name => "description"}/
    = csrf_meta_tags
    = yield :head
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
  %body
    = render :partial => 'layouts/navigation'
    .container-fluid
      .row-fluid
        - if user_signed_in?
          .span3
            %h2= current_wedding.name
            = render :partial => 'layouts/stats'
        .span9
          = bootstrap_flash
          = yield :heading
          = yield :filters
          = yield
      %footer
    #farmlywed-modal.modal.hide.fade{"data-backdrop" => "static"}
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h3
      .modal-body
      .modal-footer
    = javascript_include_tag "application"
    :javascript
      $(document).ready(function() { loadGuestStats(); });